import mongoose from "mongoose";
const userSchema=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    password:{
        type:String,
        required:true,
        minlength:6
    },
    gender:{
        type:String,
        required:true,
        enum:["male","female"],
    },
    profilePic:{
        type:String,
        default:"",
    },
    address:{
        street:String,
        city:String,
        state:String,
        zip:String,
        country:String
    },
    cart:[
        {
            productId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'Product'
            },
            quantity:{
                type:Number,
                default:1,
            }
        }
    ],
    orders:[
        {
            orderId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'Order'
            },
            date:{
                type:Date,
                default:Date.now
            }
        }
    ],
    wishlist:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Product'
        }
    ]
},{timestamps:true});

const User=mongoose.model('User',userSchema);
export default User;